import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";
import { nameSchema, type Name } from "./name.js";
import { phoneWithTypeSchema, type PhoneWithType } from "./phone-with-type.js";

/** The details about a customer in PayPal's system of record. */
export type CardCustomerInformation = {
  /** The unique ID for a customer generated by PayPal. */
  id?: string;
  /**
   * The internationalized email address. Note: Up to 64 characters are allowed before and 255
   * characters are allowed after the \@ sign. However, the generally accepted maximum length for an
   * email address is 254 characters. The pattern verifies that an unquoted \@ sign exists.
   */
  emailAddress?: string;
  /** The phone information. */
  phone?: PhoneWithType;
  /** The name of the party. */
  name?: Name;
  /**
   * Merchants and partners may already have a data-store where their customer information is
   * persisted. Use merchant_customer_id to associate the PayPal-generated customer.id to your
   * representation of a customer.
   */
  merchantCustomerId?: string;
};

export const cardCustomerInformationSchema: Schema<CardCustomerInformation> =
  s.object<CardCustomerInformation>({
    id: s.optional(s.string()),
    emailAddress: s.optional(s.string()),
    phone: s.optional(s.lazy(() => phoneWithTypeSchema)),
    name: s.optional(s.lazy(() => nameSchema)),
    merchantCustomerId: s.optional(s.string()),
    _keysMap: {
      emailAddress: "email_address",
      merchantCustomerId: "merchant_customer_id",
    },
  });
