import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";

/** Customer in merchant's or partner's system of records. */
export type CustomerResponse = {
  /** The unique ID for a customer generated by PayPal. */
  id?: string;
  /**
   * Merchants and partners may already have a data-store where their customer information is
   * persisted. Use merchant_customer_id to associate the PayPal-generated customer.id to your
   * representation of a customer.
   */
  merchantCustomerId?: string;
};

export const customerResponseSchema: Schema<CustomerResponse> = s.object<CustomerResponse>({
  id: s.optional(s.string()),
  merchantCustomerId: s.optional(s.string()),
  _keysMap: {
    merchantCustomerId: "merchant_customer_id",
  },
});
