import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";

/**
 * This object defines a customer in your system. Use it to manage customer profiles, save payment
 * methods and contact details.
 */
export type Customer = {
  /** The unique ID for a customer generated by PayPal. */
  id?: string;
  /**
   * Merchants and partners may already have a data-store where their customer information is
   * persisted. Use merchant_customer_id to associate the PayPal-generated customer.id to your
   * representation of a customer.
   */
  merchantCustomerId?: string;
};

export const customerSchema: Schema<Customer> = s.object<Customer>({
  id: s.optional(s.string()),
  merchantCustomerId: s.optional(s.string()),
  _keysMap: {
    merchantCustomerId: "merchant_customer_id",
  },
});
