import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";

/**
 * This object defines a customer in your system. Use it to manage customer profiles, save payment
 * methods and contact details.
 */
export type VaultResponseCustomer = {
  /** The unique ID for a customer generated by PayPal. */
  id?: string;
  /**
   * Merchants and partners may already have a data-store where their customer information is
   * persisted. Use merchant_customer_id to associate the PayPal-generated customer.id to your
   * representation of a customer.
   */
  merchantCustomerId?: string;
  /** DEPRECATED. This field is DEPRECATED. */
  links?: Record<string, unknown>[];
};

export const vaultResponseCustomerSchema: Schema<VaultResponseCustomer> = s.object<VaultResponseCustomer>({
  id: s.optional(s.string()),
  merchantCustomerId: s.optional(s.string()),
  links: s.optional(s.array(s.record(s.string(), s.unknown()))),
  _keysMap: {
    merchantCustomerId: "merchant_customer_id",
  },
});
