import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";
import { nameSchema, type Name } from "./name.js";

/**
 * This object represents a merchant’s customer, allowing them to store contact details, and track
 * all payments associated with the same customer.
 */
export type VaultCustomer = {
  /** The unique ID for a customer generated by PayPal. */
  id?: string;
  /** The name of the party. */
  name?: Name;
};

export const vaultCustomerSchema: Schema<VaultCustomer> = s.object<VaultCustomer>({
  id: s.optional(s.string()),
  name: s.optional(s.lazy(() => nameSchema)),
});
