import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";
import { nameSchema, type Name } from "./name.js";
import { phoneWithTypeSchema, type PhoneWithType } from "./phone-with-type.js";

/** The details about a customer in PayPal's system of record. */
export type VenmoWalletCustomerInformation = {
  /** The unique ID for a customer generated by PayPal. */
  id?: string;
  /**
   * The internationalized email address. Note: Up to 64 characters are allowed before and 255
   * characters are allowed after the \@ sign. However, the generally accepted maximum length for an
   * email address is 254 characters. The pattern verifies that an unquoted \@ sign exists.
   */
  emailAddress?: string;
  /** The phone information. */
  phone?: PhoneWithType;
  /** The name of the party. */
  name?: Name;
};

export const venmoWalletCustomerInformationSchema: Schema<VenmoWalletCustomerInformation> =
  s.object<VenmoWalletCustomerInformation>({
    id: s.optional(s.string()),
    emailAddress: s.optional(s.string()),
    phone: s.optional(s.lazy(() => phoneWithTypeSchema)),
    name: s.optional(s.lazy(() => nameSchema)),
    _keysMap: {
      emailAddress: "email_address",
    },
  });
